apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana_helmrepo.yaml
  - grafana_helmrelease.yaml
  - opentelemetry-operator.yaml

metadata:
  namespace: observability
