apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana_helmrepo.yaml
  - grafana_helmrelease.yaml
  - namespace.yaml
  - loki.hr.yaml
  - mimir.hr.yaml
  - tempo.hr.yaml
# metadata:
#   namespace: observability
